apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mal-config
                  key: postgres.user
            # - name: DB_HOST
            #   value: db-cluster-service
            - name: DB_PORT
              value: "5432"
            # - name: DB_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: mal-config
            #       key: postgres.port
            # - name: DB_NAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: mal-config
            #       key: postgres.name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mal-secret
                  key: db_password